apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-tracer.yaml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: neon-rpc
  name: neon-rpc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neon-rpc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-tracer.yaml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: neon-rpc
    spec:
      containers:
        - image: neonlabsorg/neon-rpc:ci-eip-1898
          name: neon-rpc
          ports:
            - containerPort: 9090
          resources: {}
      hostname: neon-rpc
      restartPolicy: Always
status: {}
