proxyCount: 1
keysPerProxy: 2

clusterType: "localhost"
environment: devnet

onePod:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  host: ""

image:
  repository: neonlabsorg/proxy
  pullPolicy: Always
  tag: "v0.11.2"

resources:
  requests:
    cpu: 500m
    memory: 2G        
  limits:
    cpu: 1000m            
    memory: 4G

serviceAccount:
  create: true
  annotations: {}
  name: "neon-proxy-sa"

podAnnotations: {}

service:
  name: proxy-svc
  type: ClusterIP
  sessionAffinity: ClientIP
  clusterIP: None
  port: 9090
  protocol: TCP
  labels: {}

extraPorts:
  - port: 9092
    containerPort: 9092
    protocol: TCP
    name: service-port
  - port: 8888
    containerPort: 8888
    protocol: TCP
    name: exporter

envFrom:
  - secretRef: 
      name: postgres-secret
  - secretRef: 
      name: proxy-config

proxyEnv: {}

solanaUrl: ""
ppsolanaUrl: ""

volumes: 
  - name: proxy-keys-script
    configMap:
      name: proxy-keys-script
      defaultMode: 0777

volumeMounts: 
  - name: proxy-keys-script
    mountPath: /root/.config/solana/scripts/get_keys.sh
    subPath: get_keys.sh
  - name: proxy-keys-script
    mountPath: /opt/proxy/run-proxy.sh
    subPath: run-proxy.sh
  - name: proxy-keys-script
    mountPath: /opt/proxy/run-indexer.sh
    subPath: run-indexer.sh

indexer:
  service:
    name: indexer-svc
    type: ClusterIP
    port: 8887
    protocol: TCP
  LOG_FULL_OBJECT_INFO: ""
  GATHER_STATISTICS: ""
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
 



